---
image: circleci/ruby:3.0.3-node-browsers

variables:
  POSTGRES_HOST: postgres
  POSTGRES_DB: thape_web_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  CACHE_FALLBACK_KEY: "$CI_COMMIT_REF_SLUG"

before_script:
  - bundle config mirror.https://rubygems.org https://gems.ruby-china.com
  - bundle config set path 'vendor'  # Install dependencies into ./vendor/ruby

stages:
  - test
  - deploy

test:
  services:
    - postgres:12.9
  stage: test
  cache:
    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/ruby
    - key:
        files:
          - yarn.lock
      paths:
        - ".yarn-cache/"
  variables:
    DATABASE_URL: postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB
  script:
    - bundle install -j $(nproc)
    - yarn install --cache-folder .yarn-cache
    - cp config/database.yml.sample.yaml config/database.yml
    - bin/rails db:drop RAILS_ENV=test
    - bin/rails db:setup RAILS_ENV=test
    - bin/rails test
