---
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'lib/templates/**/*'
    - 'lib/tasks/release.rake'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'bin/**/*'
  DisabledByDefault: true
  TargetRubyVersion: 3.0

Style/FrozenStringLiteralComment:
  Enabled: false
