# frozen_string_literal: true

require "test_helper"
require "tempfile"

class Admin::AdminTest < ActionDispatch::IntegrationTest
  parallelize(workers: 1)

  setup do
    # The checked-in PostgreSQL snapshot omits the live database's identity
    # metadata. Restore it transactionally in test only, for real create tests.
    connection = ActiveRecord::Base.connection
    connection.select_rows(<<~SQL).each do |table, _|
      SELECT table_name, column_name FROM information_schema.columns
      WHERE table_schema = current_schema() AND column_name = 'id'
      AND data_type = 'bigint' AND column_default IS NULL AND is_identity = 'NO'
    SQL
      quoted = connection.quote_table_name(table)
      next_id = connection.select_value("SELECT COALESCE(MAX(id), 0) + 1 FROM #{quoted}").to_i
      connection.execute("ALTER TABLE #{quoted} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH #{next_id})")
    end
    @user = Admin::User.create!(name: "Admin", email: "admin@example.test", password: "admin-test-password")
    @upload_root = Dir.mktmpdir("admin-uploads")
    @original_upload_root = CarrierWave::Uploader::Base.root
    CarrierWave::Uploader::Base.root = @upload_root
  end

  teardown do
    CarrierWave::Uploader::Base.root = @original_upload_root
    FileUtils.remove_entry(@upload_root) if @upload_root && File.exist?(@upload_root)
  end

  def sign_in
    post admin_login_path, params: {session: {email: " ADMIN@example.test ", password: "admin-test-password"}}
    assert_response :redirect
  end

  def path(resource, action, record = nil, **options)
    id = record&.id
    id ||= 1 if resource.singleton? && %w[home about service_files].include?(resource.key)
    url_for(controller: "admin/#{resource.key}", action: action, id: id, only_path: true, **options)
  end

  def attributes_for(key)
    case key
    when "users" then {name: "Another admin", email: "another@example.test", password: "new-password", password_confirmation: "new-password"}
    when "works" then {project_name: "Test work", city_id: cities(:city_1).id, published: false}
    when "people" then {name: "测试姓名", url_name: "admin-test-person", category: 1}
    when "infos" then {title: "测试新闻", introduction: "引言", content: "<p>正文</p>", category: 1}
    when "pictures" then {image: upload("picture.png", "image/png")}
    when "cities" then {name: "测试城市", url_name: "admin-test-city"}
    when "cases" then {title: "测试项目", professional: ["1", "2"], market: ["1"]}
    when "publications" then {title: "测试出版物", category_status: "monographs"}
    when "portfolios", "insights" then {title: "测试文档", sub_title: "副标题"}
    else {}
    end
  end

  def upload(name, type)
    file = Tempfile.new(["admin", File.extname(name)])
    file.binmode
    file.write((type == "application/pdf") ? "%PDF-1.4\n%%EOF" : Base64.decode64("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aXioAAAAASUVORK5CYII="))
    file.rewind
    Rack::Test::UploadedFile.new(file.path, type, original_filename: name)
  ensure
    file&.close!
  end

  test "every admin endpoint requires authentication" do
    Rails.application.routes.routes.each do |route|
      controller = route.defaults[:controller].to_s
      next unless controller.start_with?("admin/") && controller != "admin/sessions"
      endpoint = route.path.spec.to_s.sub("(.:format)", "").gsub(/:\w+/, "1")
      verb = route.verb.downcase
      next unless %w[get post patch put delete].include?(verb)
      public_send(verb, endpoint)
      assert_response :redirect, endpoint
      assert_equal "/admin/login", URI(response.location).path, endpoint
    end
  end

  test "existing bcrypt accounts can log in and logout invalidates access" do
    assert @user.password_digest.start_with?("$2a$")
    post admin_login_path, params: {session: {email: @user.email, password: "incorrect"}}
    assert_response :unprocessable_entity
    sign_in
    get admin_root_path
    assert_response :success
    assert_select "nav a", count: Admin::Resource.all.size
    assert_select 'script[src*="admin"]'
    assert_select 'script[src*="application"]', count: 0
    delete admin_logout_path
    get admin_users_path
    assert_equal "/admin/login", URI(response.location).path
  end

  test "all indexes new pages and singleton pages render" do
    sign_in
    Admin::Resource.all.each do |resource|
      [:index, :new, :edit, :show].each do |action|
        next unless resource.allows?(action)
        next if [:edit, :show].include?(action) && !resource.singleton?
        get path(resource, action)
        assert_response :success, "#{resource.key}##{action}: #{response.body.first(300)}"
        assert_select "h1", minimum: 1
      end
    end
  end

  test "all creatable resources persist and their edit and show pages render" do
    sign_in
    Admin::Resource.all.select { |resource| resource.allows?(:create) }.each do |resource|
      assert_difference -> { resource.scope.count }, 1, resource.key do
        post path(resource, :create), params: {resource.param_key => attributes_for(resource.key)}
        assert_response :redirect, "#{resource.key}: #{response.body.first(500)}"
      end
      record = resource.scope.order(:id).last
      [:edit, :show].each do |action|
        next unless resource.allows?(action)
        get path(resource, action, record)
        assert_response :success, "#{resource.key}##{action}"
      end
      if resource.allows?(:update)
        attributes = attributes_for(resource.key)
        patch path(resource, :update, record), params: {resource.param_key => attributes}
        assert_response :redirect, "#{resource.key}#update"
      end
      if resource.allows?(:destroy)
        delete path(resource, :destroy, record)
        assert_response :redirect, "#{resource.key}#destroy"
        assert_not resource.scope.exists?(record.id), resource.key
      end
    end
  end

  test "singletons initialize on save and every metadata editor persists" do
    sign_in
    Admin::Resource.all.select(&:singleton?).each do |resource|
      field = resource.fields.find { |_key, options| options["type"] != "file_field" }&.first
      field ||= resource.fields.keys.first
      value = (resource.fields[field]["type"] == "file_field") ? upload("image.png", "image/png") : "Saved text"
      value = infos(:info_635).id if field.end_with?("_id")
      patch path(resource, :update), params: {resource.param_key => {field => value}}
      assert_response :redirect, resource.key
      assert resource.scope.first.public_send(field).present?, resource.key
    end
    contact = MapContact.create!(name: "Shanghai")
    get edit_admin_map_contact_path(contact)
    assert_response :success
    patch admin_map_contact_path(contact), params: {map_contact: {address: "New address"}}
    assert_equal "New address", contact.reload.address
    seo = Seo.first
    patch admin_seo_path(seo), params: {seo: {home_title: "Updated title"}}
    assert_equal "Updated title", seo.reload.home_title
  end

  test "unpublished works are editable only through admin and translations stay separate" do
    sign_in
    post admin_works_path, params: {work: attributes_for("works")}
    work = Admin::Work.unscoped.order(:id).last
    assert_not Work.exists?(work.id)
    get admin_works_path(q: "Test work")
    assert_select "td", text: "Test work"
    patch admin_work_path(work, locale: :en), params: {work: {project_name: "English name", published: true}}
    assert_response :redirect
    assert Work.exists?(work.id)
    assert_equal "English name", Globalize.with_locale(:en) { work.reload.project_name }
    assert_equal "Test work", Globalize.with_locale(:cn) { work.reload.project_name }
    patch admin_work_path(work), params: {work: {published: false}}
    assert_not Work.exists?(work.id)
  end

  test "work categories and paired gallery uploads can be created updated and removed" do
    sign_in
    type = ProjectType.first
    residential = ResidentialType.create!(cn_name: "住宅")
    attrs = attributes_for("works").merge(project_type_ids: [type.id], residential_type_ids: [residential.id], snapshot_jpg: upload("cover.jpg", "image/jpeg"), work_pictures_attributes: {"0" => {album_jpg: upload("gallery.jpg", "image/jpeg"), album_webp: upload("gallery.webp", "image/webp")}})
    post admin_works_path, params: {work: attrs}
    assert_response :redirect, response.parsed_body.css('[role="alert"]').text
    work = Admin::Work.unscoped.order(:id).last
    assert_equal [type.id], work.project_type_ids
    assert_equal [residential.id], work.residential_type_ids
    assert_equal 1, work.work_pictures.count
    assert_includes work.snapshot_jpg.url, "/uploads/work/snapshot_jpg/#{work.id}/"
    picture = work.work_pictures.first
    assert picture.album_webp.present?
    patch admin_work_path(work), params: {work: {project_type_ids: [""], residential_type_ids: [""], work_pictures_attributes: {"0" => {id: picture.id, _destroy: "1"}}}}
    assert_response :redirect
    assert_empty work.reload.project_type_ids
    assert_empty work.residential_type_ids
    assert_empty work.work_pictures
  end

  test "city memberships and localized city roles persist and can be removed" do
    sign_in
    city = cities(:city_1)
    post admin_people_path, params: {person: attributes_for("people").merge(city_ids: [city.id])}
    person = Admin::Person.order(:id).last
    role = person.city_people.first
    patch admin_person_path(person), params: {person: {city_people_attributes: {"0" => {id: role.id, city_title: "总监", city_en_title: "Director", is_management: "1", is_professional: "1"}}}}
    assert_response :redirect
    assert_equal "Director", role.reload.city_en_title
    assert role.is_management
    delete destory_city_people_admin_person_path(person, city_people_id: role.id)
    assert_empty person.reload.city_people
  end

  test "removing a city from the complete edit form does not update its deleted role" do
    sign_in
    person = Admin::Person.create!(attributes_for("people").merge(city_ids: [cities(:city_1).id, cities(:city_5).id]))
    removed, retained = person.city_people.order(:city_id).to_a
    patch admin_person_path(person), params: {person: {city_ids: [retained.city_id], city_people_attributes: {"0" => {id: removed.id, city_title: "removed"}, "1" => {id: retained.id, city_title: "retained"}}}}
    assert_response :redirect
    assert_equal [retained.city_id], person.reload.city_ids
    assert_equal "retained", retained.reload.city_title
  end

  test "failed edits roll back association changes and foreign nested IDs are rejected" do
    sign_in
    person = Admin::Person.create!(attributes_for("people").merge(city_ids: [cities(:city_1).id]))
    other = Admin::Person.create!(url_name: "other-person", city_ids: [cities(:city_5).id])
    patch admin_person_path(person), params: {person: {url_name: other.url_name, city_ids: [cities(:city_18).id]}}
    assert_response :unprocessable_entity
    assert_equal [cities(:city_1).id], person.reload.city_ids
    patch admin_person_path(person), params: {person: {city_people_attributes: {"0" => {id: other.city_people.first.id, city_title: "wrong owner"}}}}
    assert_response :not_found
    assert_nil other.city_people.first.reload.city_title
  end

  test "classic case galleries retain their legacy paths and delete with the case" do
    sign_in
    post admin_cases_path, params: {case: attributes_for("cases").merge(case_pictures_attributes: {"0" => {album: upload("case.png", "image/png")}, "1" => {album_cache: ""}})}
    assert_response :redirect
    record = Admin::Case.order(:id).last
    assert_equal [1, 2], JSON.parse(record.professional)
    assert_equal 1, record.case_pictures.count
    picture = record.case_pictures.first
    assert_includes picture.album.url, "/uploads/case_picture/album/#{picture.id}/"
    delete admin_case_path(record)
    assert_not Admin::CasePicture.exists?(picture.id)
  end

  test "admin locale and assets stay separate from customer pages" do
    sign_in
    get admin_root_path(locale: :en)
    assert_response :success
    get root_path(locale: :cn)
    assert_response :success
    assert_select 'script[src*="application"]', minimum: 1
    assert_select 'script[src*="admin"]', count: 0
    get admin_root_path
    assert_select 'html[lang="en"]'
    get "/"
    assert_response :success
    assert_equal "cn", cookies["locale"]
  end

  test "news content remains a textarea and metadata updates cannot change positions" do
    sign_in
    info = Admin::Info.create!(attributes_for("infos"))
    position = info.position
    get edit_admin_info_path(info)
    assert_select 'textarea[name="info[content]"]', text: "<p>正文</p>"
    patch admin_info_path(info), params: {info: {title: "Updated", position: 99999, pdf_file: upload("news.pdf", "application/pdf")}}
    assert_response :redirect
    assert_equal position, info.reload.position
    assert_equal "<p>正文</p>", info.content
    assert_includes info.pdf_file.url, "/uploads/info/pdf_file/#{info.id}/"
    %w[infos works people cases].each do |resource|
      %w[top bottom up down].each do |action|
        assert_raises(ActionController::RoutingError) { Rails.application.routes.recognize_path("/admin/#{resource}/1/#{action}", method: :patch) }
      end
    end
  end

  test "invalid saves return errors without discarding submitted content" do
    sign_in
    assert_no_difference "Info.count" do
      post admin_infos_path, params: {info: {title: "Retained title", introduction: "", content: "Retained content"}}
      assert_response :unprocessable_entity
      assert_select '[role="alert"]'
      assert_select 'input[name="info[title]"][value="Retained title"]'
    end
    assert_no_difference "Admin::User.count" do
      post admin_users_path, params: {user: {name: "Invalid", email: "bad", password: "short", password_digest: @user.password_digest}}
      assert_response :unprocessable_entity
    end
    delete admin_user_path(@user)
    assert Admin::User.exists?(@user.id)
  end

  test "messages display escaped content export all rows and can be deleted" do
    sign_in
    [GuestMessage, ProjectMessage].each do |model|
      record = model.create!(name: "=SUM(1,2)", company: "Company", message: "<script>alert(1)</script>", spam_score: 7)
      resource = Admin::Resource.new((model == GuestMessage) ? "message" : "project_messages")
      get path(resource, :show, record)
      assert_response :success
      assert_select "script", text: "alert(1)", count: 0
      assert_includes response.body, "&lt;script&gt;"
      get path(resource, :index, nil, format: :csv, per_page: 1)
      assert_response :success
      assert response.body.start_with?("\uFEFF")
      assert_includes response.body, "'=SUM(1,2)"
      assert_includes response.headers["Content-Disposition"], ".csv"
      delete path(resource, :destroy, record)
      assert_not model.exists?(record.id)
    end
  end
end
