# frozen_string_literal: true

require "test_helper"
require "tempfile"

class Admin::AdminTest < ActionDispatch::IntegrationTest
  parallelize(workers: 1)

  setup do
    # The checked-in PostgreSQL snapshot omits the live database's identity
    # metadata. Restore it transactionally in test only, for real create tests.
    connection = ActiveRecord::Base.connection
    connection.select_rows(<<~SQL).each do |table, _|
      SELECT table_name, column_name FROM information_schema.columns
      WHERE table_schema = current_schema() AND column_name = 'id'
      AND data_type = 'bigint' AND column_default IS NULL AND is_identity = 'NO'
    SQL
      quoted = connection.quote_table_name(table)
      next_id = connection.select_value("SELECT COALESCE(MAX(id), 0) + 1 FROM #{quoted}").to_i
      connection.execute("ALTER TABLE #{quoted} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH #{next_id})")
    end
    @user = Admin::User.create!(name: "Admin", email: "admin@example.test", password: "admin-test-password")
    @upload_root = Dir.mktmpdir("admin-uploads")
    @original_upload_root = CarrierWave::Uploader::Base.root
    CarrierWave::Uploader::Base.root = @upload_root
  end

  teardown do
    CarrierWave::Uploader::Base.root = @original_upload_root
    FileUtils.remove_entry(@upload_root) if @upload_root && File.exist?(@upload_root)
  end

  def sign_in
    post admin_login_path, params: {session: {email: " ADMIN@example.test ", password: "admin-test-password"}}
    assert_response :redirect
  end

  def path(resource, action, record = nil, **options)
    id = record&.id
    id ||= 1 if resource.singleton? && resource.key == "service_files"
    url_for(controller: "admin/#{resource.key}", action: action, id: id, only_path: true, **options)
  end

  def attributes_for(key)
    case key
    when "users" then {name: "Another admin", email: "another@example.test", password: "new-password", password_confirmation: "new-password"}
    when "works" then {project_name: "Test work", city_id: cities(:city_1).id, published: false}
    when "people" then {name: "测试姓名", url_name: "admin-test-person", category: 1}
    when "infos" then {title: "测试新闻", introduction: "引言", content: "<p>正文</p>", category: 1}
    when "pictures" then {image: upload("picture.png", "image/png")}
    when "cities" then {name: "测试城市", url_name: "admin-test-city"}
    when "publications" then {title: "测试出版物", category_status: "monographs"}
    when "portfolios", "insights" then {title: "测试文档", sub_title: "副标题"}
    else {}
    end
  end

  def upload(name, type)
    file = Tempfile.new(["admin", File.extname(name)])
    file.binmode
    file.write((type == "application/pdf") ? "%PDF-1.4\n%%EOF" : Base64.decode64("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aXioAAAAASUVORK5CYII="))
    file.rewind
    Rack::Test::UploadedFile.new(file.path, type, original_filename: name)
  ensure
    file&.close!
  end

  test "every admin endpoint requires authentication" do
    Rails.application.routes.routes.each do |route|
      controller = route.defaults[:controller].to_s
      next unless controller.start_with?("admin/") && controller != "admin/sessions"
      endpoint = route.path.spec.to_s.sub("(.:format)", "").gsub(/:\w+/, "1")
      verb = route.verb.downcase
      next unless %w[get post patch put delete].include?(verb)
      public_send(verb, endpoint)
      assert_response :redirect, endpoint
      assert_equal "/admin/login", URI(response.location).path, endpoint
    end
  end

  test "existing bcrypt accounts can log in and logout invalidates access" do
    assert @user.password_digest.start_with?("$2a$")
    post admin_login_path, params: {session: {email: @user.email, password: "incorrect"}}
    assert_response :unprocessable_entity
    sign_in
    get admin_root_path
    assert_response :success
    assert_select ".admin-sidebar nav a", count: Admin::Resource.all.size + 1
    assert_select "dialog nav a", count: Admin::Resource.all.size + 1
    assert_select '.admin-sidebar nav a[aria-current="page"]', text: "工作台"
    assert_select 'a[href^="/admin/about/"]', count: 0
    assert_select 'a[href^="/admin/home/"]', count: 0
    assert_select 'a[href^="/admin/cases"]', count: 0
    assert_select '.admin-sidebar nav a[href^="/admin/about_page/edit"]', count: 1
    assert_select '.admin-sidebar nav a[href^="/admin/tail_home/edit"]', count: 1
    assert_select 'script[src*="admin"]'
    assert_select 'script[src*="application"]', count: 0
    delete admin_logout_path
    get admin_users_path
    assert_equal "/admin/login", URI(response.location).path
  end

  test "legacy home and about maintenance endpoints are no longer routed" do
    %w[home about].each do |resource|
      {"/admin/#{resource}/1" => [:get, :patch, :put], "/admin/#{resource}/1/edit" => [:get]}.each do |endpoint, methods|
        methods.each do |method|
          assert_raises(ActionController::RoutingError) do
            Rails.application.routes.recognize_path(endpoint, method: method)
          end
        end
      end
    end
  end

  test "legacy case maintenance endpoints are no longer routed" do
    {
      "/admin/cases" => [:get, :post],
      "/admin/cases/new" => [:get],
      "/admin/cases/1" => [:get, :patch, :put, :delete],
      "/admin/cases/1/edit" => [:get],
      "/admin/cases/1/reorder" => [:patch],
      "/admin/cases/1/destory_picture" => [:delete]
    }.each do |endpoint, methods|
      methods.each do |method|
        assert_raises(ActionController::RoutingError) do
          Rails.application.routes.recognize_path(endpoint, method: method)
        end
      end
    end
  end

  test "all indexes new pages and singleton pages render" do
    sign_in
    Admin::Resource.all.each do |resource|
      [:index, :new, :edit, :show].each do |action|
        next unless resource.allows?(action)
        next if [:edit, :show].include?(action) && !resource.singleton?
        get path(resource, action)
        assert_response :success, "#{resource.key}##{action}: #{response.body.first(300)}"
        assert_select "h1", minimum: 1
        if [:new, :edit].include?(action)
          assert_select "textarea[data-admin-rich-text]", count: resource.fields.count { |_field, options| options["rich_text"] }
          resource.fields.each do |field, options|
            name = "#{resource.param_key}[#{field}]#{"[]" if options["type"] == "multiple"}"
            assert_select "form.admin-editor [name=?]", name, minimum: 1, message: "#{resource.key}: missing #{field} from editor sections"
          end
        end
      end
    end
  end

  test "rich text image uploads return a picture URL and validation failures" do
    sign_in
    assert_difference "Picture.count", 1 do
      post upload_admin_pictures_path, params: {upload_file: upload("editor.png", "image/png")}
      assert_response :success
    end
    picture = Picture.order(:id).last
    assert_equal true, response.parsed_body["success"]
    assert_equal picture.image.url, response.parsed_body["file_path"]
    assert File.exist?(picture.image.path)

    assert_no_difference "Picture.count" do
      post upload_admin_pictures_path
      assert_response :unprocessable_entity
    end
    assert_equal false, response.parsed_body["success"]
    assert response.parsed_body["msg"].present?
  end

  test "rich text image uploads retain CSRF protection" do
    sign_in
    original = ActionController::Base.allow_forgery_protection
    ActionController::Base.allow_forgery_protection = true
    get new_admin_info_path
    token = response.parsed_body.at_css('meta[name="csrf-token"]')["content"]
    assert_no_difference "Picture.count" do
      post upload_admin_pictures_path, params: {upload_file: upload("rejected.png", "image/png")}
      assert_response :unprocessable_entity
    end
    post upload_admin_pictures_path, params: {authenticity_token: token, upload_file: upload("editor.png", "image/png")}
    assert_response :success
    assert_equal true, response.parsed_body["success"]
  ensure
    ActionController::Base.allow_forgery_protection = original
  end

  test "all creatable resources persist and their edit and show pages render" do
    sign_in
    Admin::Resource.all.select { |resource| resource.allows?(:create) }.each do |resource|
      assert_difference -> { resource.scope.count }, 1, resource.key do
        post path(resource, :create), params: {resource.param_key => attributes_for(resource.key)}
        assert_response :redirect, "#{resource.key}: #{response.body.first(500)}"
      end
      record = resource.scope.order(:id).last
      [:edit, :show].each do |action|
        next unless resource.allows?(action)
        get path(resource, action, record)
        assert_response :success, "#{resource.key}##{action}"
      end
      if resource.allows?(:update)
        attributes = attributes_for(resource.key)
        patch path(resource, :update, record), params: {resource.param_key => attributes}
        assert_response :redirect, "#{resource.key}#update"
      end
      if resource.allows?(:destroy)
        delete path(resource, :destroy, record)
        assert_response :redirect, "#{resource.key}#destroy"
        assert_not resource.scope.exists?(record.id), resource.key
      end
    end
  end

  test "singletons initialize on save and every metadata editor persists" do
    sign_in
    Admin::Resource.all.select(&:singleton?).each do |resource|
      field = resource.fields.find { |_key, options| options["type"] != "file_field" }&.first
      field ||= resource.fields.keys.first
      value = (resource.fields[field]["type"] == "file_field") ? upload("image.png", "image/png") : "Saved text"
      value = infos(:info_635).id if field.end_with?("_id")
      patch path(resource, :update), params: {resource.param_key => {field => value}}
      assert_response :redirect, resource.key
      assert resource.scope.first.public_send(field).present?, resource.key
    end
    contact = MapContact.create!(name: "Shanghai")
    get edit_admin_map_contact_path(contact)
    assert_response :success
    patch admin_map_contact_path(contact), params: {map_contact: {address: "New address"}}
    assert_equal "New address", contact.reload.address
    seo = Seo.first
    patch admin_seo_path(seo), params: {seo: {home_title: "Updated title"}}
    assert_equal "Updated title", seo.reload.home_title
  end

  test "residential category images can be maintained from the work type page" do
    sign_in
    resource = Admin::Resource.new("work_type_pages")

    get path(resource, :edit)
    assert_response :success
    paired_fields = %w[resdential residential_residence residential_community residential_rental demonstration_zone].flat_map do |category|
      %w[jpg webp].map { |format| "work_type_page[#{category}_#{format}]" }
    end
    assert_equal paired_fields, css_select('.admin-fields input[type="file"]').first(10).map { |input| input["name"] }

    patch path(resource, :update), params: {
      work_type_page: {
        residential_residence_jpg: upload("residence.jpg", "image/jpeg"),
        residential_residence_webp: upload("residence.webp", "image/webp"),
        residential_community_jpg: upload("community.jpg", "image/jpeg"),
        residential_community_webp: upload("community.webp", "image/webp"),
        residential_rental_jpg: upload("rental.jpg", "image/jpeg"),
        residential_rental_webp: upload("rental.webp", "image/webp")
      }
    }

    assert_response :redirect
    page = WorkTypePage.first
    %w[residence community rental].each do |category|
      %w[jpg webp].each do |format|
        uploader = page.public_send("residential_#{category}_#{format}")
        assert_equal "#{category}.#{format}", uploader.identifier
        assert File.exist?(uploader.path)
      end
    end

    get path(resource, :edit)
    %w[residence community rental].each do |category|
      assert_select "input[type='checkbox'][name='work_type_page[remove_residential_#{category}_webp]']"
    end

    patch path(resource, :update), params: {
      work_type_page: %w[residence community rental].to_h { |category| ["remove_residential_#{category}_webp", "1"] }
    }
    assert_response :redirect
    page.reload
    %w[residence community rental].each do |category|
      assert_not page.public_send("residential_#{category}_webp").present?
      assert page.public_send("residential_#{category}_jpg").present?
    end
  end

  test "unpublished works are editable only through admin and translations stay separate" do
    sign_in
    post admin_works_path, params: {work: attributes_for("works")}
    work = Admin::Work.unscoped.order(:id).last
    assert_not Work.exists?(work.id)
    get admin_works_path(q: "Test work")
    assert_select "td", text: "Test work"
    patch admin_work_path(work, locale: :en), params: {work: {project_name: "English name", published: true}}
    assert_response :redirect
    assert Work.exists?(work.id)
    assert_equal "English name", Globalize.with_locale(:en) { work.reload.project_name }
    assert_equal "Test work", Globalize.with_locale(:cn) { work.reload.project_name }
    patch admin_work_path(work), params: {work: {published: false}}
    assert_not Work.exists?(work.id)
  end

  test "work categories and paired gallery uploads can be created updated and removed" do
    sign_in
    type = ProjectType.first
    residential = ResidentialType.create!(cn_name: "住宅")
    attrs = attributes_for("works").merge(project_type_ids: [type.id], residential_type_ids: [residential.id], snapshot_jpg: upload("cover.jpg", "image/jpeg"), work_pictures_attributes: {"0" => {album_jpg: upload("gallery.jpg", "image/jpeg"), album_webp: upload("gallery.webp", "image/webp")}})
    post admin_works_path, params: {work: attrs}
    assert_response :redirect, response.parsed_body.css('[role="alert"]').text
    work = Admin::Work.unscoped.order(:id).last
    assert_equal [type.id], work.project_type_ids
    assert_equal [residential.id], work.residential_type_ids
    assert_equal 1, work.work_pictures.count
    assert_includes work.snapshot_jpg.url, "/uploads/work/snapshot_jpg/#{work.id}/"
    picture = work.work_pictures.first
    assert picture.album_webp.present?
    patch admin_work_path(work), params: {work: {project_type_ids: [""], residential_type_ids: [""], work_pictures_attributes: {"0" => {id: picture.id, _destroy: "1"}}}}
    assert_response :redirect
    assert_empty work.reload.project_type_ids
    assert_empty work.residential_type_ids
    assert_empty work.work_pictures
  end

  test "city memberships and localized city roles persist and can be removed" do
    sign_in
    city = cities(:city_1)
    post admin_people_path, params: {person: attributes_for("people").merge(city_ids: [city.id])}
    person = Admin::Person.order(:id).last
    role = person.city_people.first
    patch admin_person_path(person), params: {person: {city_people_attributes: {"0" => {id: role.id, city_title: "总监", city_en_title: "Director", is_management: "1", is_professional: "1"}}}}
    assert_response :redirect
    assert_equal "Director", role.reload.city_en_title
    assert role.is_management
    delete destory_city_people_admin_person_path(person, city_people_id: role.id)
    assert_empty person.reload.city_people
  end

  test "removing a city from the complete edit form does not update its deleted role" do
    sign_in
    person = Admin::Person.create!(attributes_for("people").merge(city_ids: [cities(:city_1).id, cities(:city_5).id]))
    removed, retained = person.city_people.order(:city_id).to_a
    patch admin_person_path(person), params: {person: {city_ids: [retained.city_id], city_people_attributes: {"0" => {id: removed.id, city_title: "removed"}, "1" => {id: retained.id, city_title: "retained"}}}}
    assert_response :redirect
    assert_equal [retained.city_id], person.reload.city_ids
    assert_equal "retained", retained.reload.city_title
  end

  test "failed edits roll back association changes and foreign nested IDs are rejected" do
    sign_in
    person = Admin::Person.create!(attributes_for("people").merge(city_ids: [cities(:city_1).id]))
    other = Admin::Person.create!(url_name: "other-person", city_ids: [cities(:city_5).id])
    patch admin_person_path(person), params: {person: {url_name: other.url_name, city_ids: [cities(:city_18).id]}}
    assert_response :unprocessable_entity
    assert_equal [cities(:city_1).id], person.reload.city_ids
    patch admin_person_path(person), params: {person: {city_people_attributes: {"0" => {id: other.city_people.first.id, city_title: "wrong owner"}}}}
    assert_response :not_found
    assert_nil other.city_people.first.reload.city_title
  end

  test "admin locale and assets stay separate from customer pages" do
    sign_in
    get admin_root_path(locale: :en)
    assert_response :success
    get root_path(locale: :cn)
    assert_response :success
    assert_select 'script[src*="application"]', minimum: 1
    assert_select 'script[src*="admin"]', count: 0
    get admin_root_path
    assert_select 'html[lang="zh-CN"]'
    assert_select '.admin-locale a[aria-current="true"]', text: "EN"
    get "/"
    assert_response :success
    assert_equal "cn", cookies["locale"]
  end

  test "news content remains a textarea and metadata updates cannot change positions" do
    sign_in
    info = Admin::Info.create!(attributes_for("infos"))
    position = info.position
    get edit_admin_info_path(info)
    assert_select 'textarea[name="info[content]"]', text: "<p>正文</p>"
    patch admin_info_path(info), params: {info: {title: "Updated", position: 99999, pdf_file: upload("news.pdf", "application/pdf")}}
    assert_response :redirect
    assert_equal position, info.reload.position
    assert_equal "<p>正文</p>", info.content
    assert_includes info.pdf_file.url, "/uploads/info/pdf_file/#{info.id}/"
    %w[infos works people].each do |resource|
      %w[top bottom up down].each do |action|
        assert_raises(ActionController::RoutingError) { Rails.application.routes.recognize_path("/admin/#{resource}/1/#{action}", method: :patch) }
      end
    end
  end

  test "all ordered resources expose ordering controls and persist every move" do
    sign_in
    %w[infos insights people portfolios publications works].each do |key|
      resource = Admin::Resource.new(key)
      record = resource.scope.create!(attributes_for(key))
      other = resource.scope.create!(attributes_for(key).merge((key == "people") ? {url_name: "other-ordered-person"} : {}))
      ids = resource.scope.order(position: :asc, id: :asc).pluck(:id)
      original_attributes = record.reload.attributes.except("position")

      get path(resource, :index)
      assert_response :success, key
      assert_select "[data-admin-order-table]", count: 1
      assert_select ".admin-order-menu", minimum: 1
      assert_equal ids.first(25), response.parsed_body.css("tr[data-record-id]").map { |row| row["data-record-id"].to_i }

      [
        ["top", {}, 0],
        ["down", {}, 1],
        ["up", {}, 0],
        ["up", {}, 0],
        ["bottom", {}, ids.length - 1],
        ["down", {}, ids.length - 1],
        ["position", {position: 2}, 1]
      ].each do |movement, options, destination|
        ids.delete(record.id)
        ids.insert(destination, record.id)
        patch path(resource, :reorder, record), params: {movement: movement, **options}
        assert_response :see_other, "#{key}: #{movement}"
        assert_equal "排序已保存", flash[:notice]
        assert_equal ids, resource.scope.order(:position).pluck(:id), "#{key}: #{movement}"
        assert_equal (0...ids.length).to_a, resource.scope.order(:position).pluck(:position)
      end
      %w[before after].each do |movement|
        ids.delete(record.id)
        ids.insert(ids.index(other.id) + ((movement == "after") ? 1 : 0), record.id)
        patch path(resource, :reorder, record), params: {movement: movement, target_id: other.id}
        assert_response :see_other
        assert_equal ids, resource.scope.order(:position).pluck(:id), "#{key}: #{movement}"
      end
      assert_equal original_attributes, record.reload.attributes.except("position"), key
    end
  end

  test "ordering repairs duplicate gaps and nulls without changing unrelated fields" do
    sign_in
    first = Portfolio.create!(title: "First", position: -10)
    second = Portfolio.create!(title: "Second", position: -10)
    third = Portfolio.create!(title: "Third", position: 50)
    last = Portfolio.create!(title: "Last", position: nil)
    resource = Admin::Resource.new("portfolios")
    ids = resource.scope.order(position: :asc, id: :asc).pluck(:id)
    ids.delete(last.id)
    ids.insert(ids.index(second.id), last.id)
    patch reorder_admin_portfolio_path(last), params: {movement: "before", target_id: second.id}
    assert_response :see_other
    assert_equal ids, Portfolio.order(:position).pluck(:id)
    assert_operator first.reload.position, :<, last.reload.position
    assert_operator second.reload.position, :<, third.reload.position
    assert_equal (0...ids.length).to_a, Portfolio.order(:position).pluck(:position)
    assert_equal "Last", last.title
  end

  test "invalid destinations do not change any positions and missing records return not found" do
    sign_in
    record = Portfolio.create!(title: "Only", position: nil)
    original = Portfolio.order(:id).pluck(:id, :position)
    [
      {movement: "unknown"},
      {movement: "position", position: ""},
      {movement: "position", position: "1.5"},
      {movement: "position", position: "0"},
      {movement: "position", position: "-1"},
      {movement: "position", position: Portfolio.count + 1},
      {movement: "before", target_id: record.id},
      {movement: "after", target_id: "99999999"},
      {movement: "after", target_id: "1 OR 1=1"}
    ].each do |parameters|
      patch reorder_admin_portfolio_path(record), params: parameters
      assert_response :see_other
      assert flash[:alert].present?
      assert_equal original, Portfolio.order(:id).pluck(:id, :position)
    end
    patch reorder_admin_portfolio_path(99999999), params: {movement: "top"}
    assert_response :not_found
    assert_equal original, Portfolio.order(:id).pluck(:id, :position)
  end

  test "moves cross pages and filters and retain locale and list context" do
    sign_in
    first = Admin::Work.unscoped.order(:position, :id).first
    hidden = Admin::Work.create!(project_name: "Ordering search", city: cities(:city_1), published: false, position: 9999)
    resource = Admin::Resource.new("works")
    ids = resource.scope.order(:position, :id).pluck(:id)
    ids.delete(hidden.id)
    ids.insert(0, hidden.id)
    patch reorder_admin_work_path(hidden, locale: :en), params: {movement: "top", q: "Ordering search", page: 2, per_page: 25}
    assert_response :see_other
    query = Rack::Utils.parse_query(URI(response.location).query)
    assert_equal({"locale" => "en", "q" => "Ordering search", "page" => "2", "per_page" => "25"}, query)
    assert_equal ids, resource.scope.order(:position).pluck(:id)
    assert_equal 1, first.reload.position
    assert_not Work.exists?(hidden.id)
    get admin_works_path(q: "Ordering search", locale: :cn)
    assert_select ".admin-order-rank", text: "1"
    assert_select 'form input[name="q"][value="Ordering search"]', minimum: 1

    before = Publication.create!(title: "Before", category_status: :monographs, position: 0)
    after = Publication.create!(title: "After", category_status: :paper_patent, position: 1)
    patch reorder_admin_publication_path(after), params: {movement: "before", target_id: before.id, category_status: "paper_patent"}
    assert_response :see_other
    assert_includes response.location, "category_status=paper_patent"
    assert_operator after.reload.position, :<, before.reload.position
  end

  test "ordering requires a CSRF token" do
    sign_in
    record = Portfolio.create!(title: "CSRF", position: 100)
    original = ActionController::Base.allow_forgery_protection
    ActionController::Base.allow_forgery_protection = true
    get admin_portfolios_path
    token = response.parsed_body.at_css('meta[name="csrf-token"]')["content"]
    patch reorder_admin_portfolio_path(record), params: {movement: "top"}
    assert_response :unprocessable_entity
    assert_equal 100, record.reload.position
    patch reorder_admin_portfolio_path(record), params: {movement: "top", authenticity_token: token}
    assert_response :see_other
    assert_equal 0, record.reload.position
  ensure
    ActionController::Base.allow_forgery_protection = original
  end

  test "new admin records append after existing positions for every ordered resource" do
    sign_in
    %w[infos insights people portfolios publications works].each do |key|
      resource = Admin::Resource.new(key)
      existing = resource.scope.create!(attributes_for(key))
      existing.update_columns(position: 5000)
      attributes = attributes_for(key).merge((key == "people") ? {url_name: "appended-person"} : {})
      post path(resource, :create), params: {resource.param_key => attributes.merge(position: 0)}
      assert_response :see_other, key
      assert_equal 5001, resource.scope.order(:id).last.position, key
    end
  end

  test "invalid saves return errors without discarding submitted content" do
    sign_in
    assert_no_difference "Info.count" do
      post admin_infos_path, params: {info: {title: "Retained title", introduction: "", content: "Retained content"}}
      assert_response :unprocessable_entity
      assert_select '[role="alert"]'
      assert_select 'input[name="info[title]"][value="Retained title"]'
    end
    assert_no_difference "Admin::User.count" do
      post admin_users_path, params: {user: {name: "Invalid", email: "bad", password: "short", password_digest: @user.password_digest}}
      assert_response :unprocessable_entity
    end
    delete admin_user_path(@user)
    assert Admin::User.exists?(@user.id)
  end

  test "messages display escaped content export all rows and can be deleted" do
    sign_in
    [GuestMessage, ProjectMessage].each do |model|
      record = model.create!(name: "=SUM(1,2)", company: "Company", message: "<script>alert(1)</script>", spam_score: 7)
      resource = Admin::Resource.new((model == GuestMessage) ? "message" : "project_messages")
      get path(resource, :show, record)
      assert_response :success
      assert_select "script", text: "alert(1)", count: 0
      assert_includes response.body, "&lt;script&gt;"
      get path(resource, :index, nil, format: :csv, per_page: 1)
      assert_response :success
      assert response.body.start_with?("\uFEFF")
      assert_includes response.body, "'=SUM(1,2)"
      assert_includes response.headers["Content-Disposition"], ".csv"
      delete path(resource, :destroy, record)
      assert_not model.exists?(record.id)
    end
  end

  test "dashboard counts include unpublished content and module destinations include singletons" do
    sign_in
    Admin::Work.create!(attributes_for("works"))
    get admin_root_path(locale: :en)
    %w[works infos people publications].each do |key|
      assert_select "[data-admin-count='#{key}']", text: Admin::Resource.new(key).scope.count.to_s
    end
    assert_select "#admin-module-results [data-admin-command-item]", count: Admin::Resource.all.size
    assert_select "#admin-module-results a[href=?]", edit_admin_tail_home_path(locale: :en)
    assert_select "#admin-module-results a[href=?]", edit_admin_service_file_path(1, locale: :en)
  end

  test "all ordered content supports literal search and translated fields use the selected language" do
    sign_in
    Admin::Resource::SEARCH_FIELDS.each do |key, field|
      resource = Admin::Resource.new(key)
      record = I18n.with_locale(:cn) { resource.scope.create!(attributes_for(key).merge(field => "组件搜索 #{key}")) }
      get path(resource, :index, nil, q: "组件搜索", locale: :cn)
      assert_response :success, key
      assert_select "tbody tr#record-#{record.id}", count: 1
      if resource.model.respond_to?(:translated_attribute_names) && resource.model.translated_attribute_names.include?(field.to_sym)
        I18n.with_locale(:en) { record.update!(field => "Component search #{key}") }
        get path(resource, :index, nil, q: "组件搜索", locale: :en)
        assert_select "tbody tr#record-#{record.id}", count: 0
        get path(resource, :index, nil, q: "Component search", locale: :en)
        assert_select "tbody tr#record-#{record.id}", count: 1
      end
    end
    literal = Admin::Info.create!(attributes_for("infos").merge(title: "100% complete"))
    Admin::Info.create!(attributes_for("infos").merge(title: "100 complete"))
    get admin_infos_path(q: "100%", locale: I18n.locale)
    assert_select "tbody tr", count: 1
    assert_select "#record-#{literal.id}"
    get admin_works_path(project_name: "组件搜索", locale: :cn)
    assert_select 'input[name="q"][value="组件搜索"]'
  end

  test "combined filters do not duplicate associated records and invalid values are ignored" do
    sign_in
    work = Admin::Work.create!(attributes_for("works").merge(project_name: "Filter work"))
    2.times { WorkProjectType.create!(work: work, project_type: project_types(:project_type_1)) }
    context = {q: "Filter work", published: "false", city_id: cities(:city_1).id, project_type_id: project_types(:project_type_1).id}
    get admin_works_path(**context)
    assert_select "tbody tr", count: 1
    assert_select "#record-#{work.id}"
    assert_select ".admin-pagination", text: /共 1 条/
    get admin_works_path(**context.merge(published: "true"))
    assert_select "tbody tr", count: 0
    get admin_works_path(q: "Filter work", published: "invalid", city_id: "-1", project_type_id: "invalid")
    assert_select "tbody tr", count: 1
    work.update_column(:published, nil)
    get admin_works_path(**context)
    assert_select "#record-#{work.id}"

    person = Admin::Person.create!(attributes_for("people"))
    2.times { CityPerson.create!(person: person, city: cities(:city_1)) }
    get admin_people_path(q: "测试姓名", category: 1, city_id: cities(:city_1).id)
    assert_select "tbody tr", count: 1
    get admin_people_path(q: "测试姓名", category: 2)
    assert_select "tbody tr", count: 0
    info = Admin::Info.create!(attributes_for("infos"))
    get admin_infos_path(q: "测试新闻", category: 1)
    assert_select "#record-#{info.id}"
    get admin_infos_path(q: "测试新闻", category: 3)
    assert_select "tbody tr", count: 0
  end

  test "pagination language changes clearing and ordering preserve normalized list state" do
    sign_in
    works = 8.times.map { |index| Admin::Work.create!(attributes_for("works").merge(project_name: "Pagination work #{index}", position: 100 + index)) }
    context = {q: "Pagination work", published: "false", city_id: cities(:city_1).id, per_page: 1, page: 4, locale: :cn}
    get admin_works_path(**context.merge(unsupported: "discard"))
    assert_select ".admin-pagination", text: /显示 4–4 条，共 8 条/
    assert_select '.admin-page-current[aria-current="page"]', text: "4"
    assert_select ".admin-page-number", text: "…", minimum: 1
    assert_select '.admin-page-number[aria-label="第 1 页"]'
    assert_select '.admin-page-number[aria-label="第 8 页"]'
    assert_select ".admin-pagination a" do |links|
      links.each do |link|
        query = Rack::Utils.parse_query(URI(link["href"]).query)
        assert_equal "false", query["published"]
        assert_equal "1", query["per_page"]
        assert_nil query["unsupported"]
      end
    end
    assert_select ".admin-locale a", text: "EN" do |links|
      query = Rack::Utils.parse_query(URI(links.first["href"]).query)
      assert_equal "false", query["published"]
      assert_nil query["page"]
    end
    assert_select "a", text: "清除筛选" do |links|
      query = Rack::Utils.parse_query(URI(links.first["href"]).query)
      assert_equal({"locale" => "cn", "per_page" => "1"}, query)
    end
    assert_select '.admin-filter-bar input[name="page"]', count: 0
    patch reorder_admin_work_path(works.last, locale: :cn), params: context.except(:locale).merge(movement: "top")
    assert_equal context.stringify_keys.transform_values(&:to_s), Rack::Utils.parse_query(URI(response.location).query)
    get admin_works_path(**context.merge(page: 1))
    assert_select '.admin-page-button[aria-disabled="true"]', text: "上一页"
    get admin_works_path(**context.merge(page: 8))
    assert_select '.admin-page-button[aria-disabled="true"]', text: "下一页"
    get admin_works_path(q: "does-not-exist", per_page: 1)
    assert_select ".admin-pagination", text: /显示 0–0 条，共 0 条/
  end

  test "picture browsing and shared field errors retain existing form contracts" do
    sign_in
    picture = Picture.create!(image: upload("component.png", "image/png"), info: infos(:info_635))
    get admin_pictures_path(per_page: 1)
    assert_select ".admin-media-card", count: 1
    assert_select ".admin-media-filename", text: "component.png"
    assert_select ".admin-media-card", text: /新闻 ID：#{infos(:info_635).id}/
    assert_select "#admin-module-search"
    get admin_pictures_path(view: "list", per_page: 1)
    assert_select "tbody tr#record-#{picture.id}"
    assert_select '.admin-view-switch a[aria-current="true"]', text: "列表"
    picture.update_column(:image, nil)
    get admin_pictures_path(view: "invalid", per_page: 1)
    assert_select ".admin-media-placeholder:not([hidden])", count: 1
    post admin_infos_path, params: {info: {title: "Retained title", introduction: "", content: ""}}
    assert_response :unprocessable_entity
    assert_select '#info_introduction[aria-invalid="true"][aria-describedby="info_introduction_error"]'
    assert_select '#info_content[aria-invalid="true"]'
    assert_select "#info_content_error", text: /Content/
    assert_select 'input[name="info[title]"][value="Retained title"]'
    assert_select '.admin-section-navigation a[href="#content-heading"]'
    assert_select 'form.admin-editor textarea[name="info[content]"][data-admin-rich-text]'
    person = Admin::Person.create!(attributes_for("people"))
    get edit_admin_person_path(person)
    assert_select '.admin-section-navigation a[href="#city-roles-heading"]'
  end
end
