---
default: &default
  corpid: <%= Rails.application.credentials.wechat_corpid! %>
  corpsecret: <%= Rails.application.credentials.wechat_corpsecret! %>
  agentid: <%= Rails.application.credentials.wechat_agentid! %>
  token: <%= Rails.application.credentials.wechat_token! %>
  access_token: "tmp/wechat_access_token"
  encrypt_mode: true
  encoding_aes_key: <%= Rails.application.credentials.wechat_encoding_aes_key! %>
  jsapi_ticket: "tmp/wechat_jsapi_ticket"

production:
  <<: *default

development:
  <<: *default
  trusted_domain_fullname: "http://your_dev.proxy.qqbrowser.cc"

test:
  <<: *default
